git-credential-helper: don't ask password when already given once

diff --git a/contrib/examples/git-credential-lastpass b/contrib/examples/git-credential-lastpass
--- a/contrib/examples/git-credential-lastpass
+++ b/contrib/examples/git-credential-lastpass
@@ -43,6 +43,7 @@ if [ "${params['protocol']}" != "https" ] || [ -z "${params["host"]}" ]; then
 fi
 
 if ! lpass status -q; then
+	lpassuser="$(cat "$HOME/.lpass/username" 2>/dev/null)"
 	if [ -z "$lpassuser" ]; then
 		read -r -p "Lastpass: login required. Lastpass username: " lpassuser </dev/tty >/dev/tty
 	fi
@@ -50,8 +51,8 @@ if ! lpass status -q; then
 		exit
 	fi
 
-	if ! lpass login "$lpassuser" >&2; then
-		echo "Lastpass: failed to login" >&2
+	if ! lpass login "$lpassuser" </dev/tty >/dev/tty >&2; then
+		echo "Lastpass: failed to login username '$lpassuser'" >&2
 		exit
 	fi
 fi
